name: Kubernetes CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Validate Kubernetes Manifests
        run: |
          kubectl apply \
            --dry-run=client \
            --validate=false \
            -f kubernetes/
